language: generic
services:
  - docker

before_install:
  - export TAG=$(date +'%Y%m%d%H%M%S')
  # - docker build -t estaton/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo "noop"
  # - docker run -e CI=true estaton/react-test npm test

after_success:
  # - docker build -t estaton/multi-client:$TAG ./client
  - docker build -t estaton/multi-nginx:$TAG -t estaton/multi-nginx ./nginx
  # - docker build -t estaton/multi-server:$TAG ./server
  # - docker build -t estaton/multi-worker:$TAG ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push them to docker hub
  # - docker push estaton/multi-client:$TAG
  - docker push estaton/multi-nginx
  # - docker push estaton/multi-server:$TAG
  # - docker push estaton/multi-worker:$TAG

# deploy:
#   provider: elasticbeanstalk
#   region: eu-central-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-eu-central-1-482265229510
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY